name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install LLVM and Clang
        run: |
          sh ./install-llvm.sh

      - name: Build
        run: |
          git clone https://github.com/smack0007/WasmImageProcessing.git -b dist ./bin
          pushd bin
          find . \! -name '.git' -delete
          popd
          make -f build.mak build

      - name: Publish
        run: |
          git log -1 --pretty=%B > commit.msg
          cd bin
          git config --global user.name "smack0007"
          git config --global user.email "zachary.snow@gmail.com"
          git add -A && git commit -F "../commit.msg"
          git push https://smack0007:${{ secrets.API_KEY }}@github.com/smack0007/WasmImageProcessing.git
